import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Navbars from "../components/navBar";
import NavBare from "../components/navBare";
import BottomHeader from "../components/headers/BottomHeader";
import Footer from "../components/footer/footer";
import RegisterModal from "@/components/modals/RegisterModal";
import LoginModal from "@/components/modals/LoginModal";
import { authOptions } from "@/lib/session";
import { getServerSession } from "next-auth/next";
import Header from "@/components/headers/Header";
import Header1 from "@/components/headers/Header1";
import { useEffect } from "react";
import Sidebar from "@/components/headers/sideBar";
import Header2 from "@/components/headers/Header2";
import BoutonTelecharger from "@/components/BoutonTelecharger";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: //container,
{
  children: React.ReactNode;
  // container: boolean;
}) {
  const session = await getServerSession(authOptions);
  const container: boolean = false;

  return (
    <html lang="en" className="light">
      <body>
        {container ? (
          <div className="container ">
            <RegisterModal />
            <LoginModal />
            <Providers session={session}>
              {/* <Header />  */}
              <Header2 />
              {/*  <Header /> */}
              <BottomHeader />
              {children}

              <Footer />
            </Providers>
          </div>
        ) : (
          <div className="px-7">
            <RegisterModal />
            <LoginModal />
            <Providers session={session}>
              {/* <Header />  */}
              <Header2 />
              {/*  <BottomHeader /> */}
              {children}

              <Footer />
            </Providers>
            <>
              <div id="container-floating">
                <div id="floating-button">
                  <BoutonTelecharger />
                </div>
              </div>
            </>
          </div>
        )}
      </body>
    </html>
  );
}
